name: Deploy to VPS without Docker Hub

on:
  push:
    branches:
      - main  # Adjust as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t myapp -f ./DockerFile .

      - name: Save Docker image as a tar file
        run: |
          docker save myapp -o myapp.tar

      - name: Copy Docker image to VPS using SCP with Password
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}  # Using password authentication
          source: "myapp.tar"
          target: "/tmp/"

      - name: Deploy on VPS using SSH with Password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            docker stop myapp || true
            docker rm myapp || true
            docker load -i /tmp/myapp.tar
            docker run -d --name myapp -p 80:3000 --restart always myapp:latest
            rm /tmp/myapp.tar  # Clean up

